package org.gaddiel.model;
// default package
// Generated Mar 12, 2012 10:32:31 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// TODO: Auto-generated Javadoc
/**
 * ChurchAddressContacts generated by hbm2java.
 */
@Entity
@Table(name="church_address_contacts"

)
public class ChurchAddressContacts  implements java.io.Serializable {


     /** The contact id. */
     private Integer contactId;
     
     /** The address id. */
     private Integer addressId;
     
     /** The custom contact type lv id. */
     private Integer customContactTypeLvId;
     
     /** The contact title. */
     private String contactTitle;
     
     /** The contact value. */
     private String contactValue;
     
     /** The description. */
     private String description;
     
     /** The remarks. */
     private String remarks;
     
     /** The enabled flag. */
     private String enabledFlag;
     
     /** The start date. */
     private Date startDate;
     
     /** The end date. */
     private Date endDate;
     
     /** The created by. */
     private String createdBy;
     
     /** The created date. */
     private Date createdDate;
     
     /** The last updated by. */
     private String lastUpdatedBy;
     
     /** The last updated date. */
     private Date lastUpdatedDate;

    /**
     * Instantiates a new church address contacts.
     */
    public ChurchAddressContacts() {
    }

	
    /**
     * Instantiates a new church address contacts.
     *
     * @param createdDate the created date
     * @param lastUpdatedDate the last updated date
     */
    public ChurchAddressContacts(Date createdDate, Date lastUpdatedDate) {
        this.createdDate = createdDate;
        this.lastUpdatedDate = lastUpdatedDate;
    }
    
    /**
     * Instantiates a new church address contacts.
     *
     * @param addressId the address id
     * @param customContactTypeLvId the custom contact type lv id
     * @param contactTitle the contact title
     * @param contactValue the contact value
     * @param description the description
     * @param remarks the remarks
     * @param enabledFlag the enabled flag
     * @param startDate the start date
     * @param endDate the end date
     * @param createdBy the created by
     * @param createdDate the created date
     * @param lastUpdatedBy the last updated by
     * @param lastUpdatedDate the last updated date
     */
    public ChurchAddressContacts(Integer addressId, Integer customContactTypeLvId, String contactTitle, String contactValue, String description, String remarks, String enabledFlag, Date startDate, Date endDate, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate) {
       this.addressId = addressId;
       this.customContactTypeLvId = customContactTypeLvId;
       this.contactTitle = contactTitle;
       this.contactValue = contactValue;
       this.description = description;
       this.remarks = remarks;
       this.enabledFlag = enabledFlag;
       this.startDate = startDate;
       this.endDate = endDate;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
    }
   
     /**
      * Gets the contact id.
      *
      * @return the contact id
      */
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CONTACT_ID", unique=true, nullable=false)
    public Integer getContactId() {
        return this.contactId;
    }
    
    /**
     * Sets the contact id.
     *
     * @param contactId the new contact id
     */
    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }

    
    /**
     * Gets the address id.
     *
     * @return the address id
     */
    @Column(name="ADDRESS_ID")
    public Integer getAddressId() {
        return this.addressId;
    }
    
    /**
     * Sets the address id.
     *
     * @param addressId the new address id
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    
    /**
     * Gets the custom contact type lv id.
     *
     * @return the custom contact type lv id
     */
    @Column(name="CUSTOM_CONTACT_TYPE_LV_ID")
    public Integer getCustomContactTypeLvId() {
        return this.customContactTypeLvId;
    }
    
    /**
     * Sets the custom contact type lv id.
     *
     * @param customContactTypeLvId the new custom contact type lv id
     */
    public void setCustomContactTypeLvId(Integer customContactTypeLvId) {
        this.customContactTypeLvId = customContactTypeLvId;
    }

    
    /**
     * Gets the contact title.
     *
     * @return the contact title
     */
    @Column(name="CONTACT_TITLE", length=120)
    public String getContactTitle() {
        return this.contactTitle;
    }
    
    /**
     * Sets the contact title.
     *
     * @param contactTitle the new contact title
     */
    public void setContactTitle(String contactTitle) {
        this.contactTitle = contactTitle;
    }

    
    /**
     * Gets the contact value.
     *
     * @return the contact value
     */
    @Column(name="CONTACT_VALUE", length=120)
    public String getContactValue() {
        return this.contactValue;
    }
    
    /**
     * Sets the contact value.
     *
     * @param contactValue the new contact value
     */
    public void setContactValue(String contactValue) {
        this.contactValue = contactValue;
    }

    
    /**
     * Gets the description.
     *
     * @return the description
     */
    @Column(name="DESCRIPTION", length=120)
    public String getDescription() {
        return this.description;
    }
    
    /**
     * Sets the description.
     *
     * @param description the new description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    
    /**
     * Gets the remarks.
     *
     * @return the remarks
     */
    @Column(name="REMARKS", length=200)
    public String getRemarks() {
        return this.remarks;
    }
    
    /**
     * Sets the remarks.
     *
     * @param remarks the new remarks
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    /**
     * Gets the enabled flag.
     *
     * @return the enabled flag
     */
    @Column(name="ENABLED_FLAG", length=1)
    public String getEnabledFlag() {
        return this.enabledFlag;
    }
    
    /**
     * Sets the enabled flag.
     *
     * @param enabledFlag the new enabled flag
     */
    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    /**
     * Gets the start date.
     *
     * @return the start date
     */
    @Temporal(TemporalType.DATE)
    @Column(name="START_DATE", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    /**
     * Sets the start date.
     *
     * @param startDate the new start date
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * Gets the end date.
     *
     * @return the end date
     */
    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    /**
     * Sets the end date.
     *
     * @param endDate the new end date
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    /**
     * Gets the created by.
     *
     * @return the created by
     */
    @Column(name="CREATED_BY", length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    /**
     * Sets the created by.
     *
     * @param createdBy the new created by
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Gets the created date.
     *
     * @return the created date
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    /**
     * Sets the created date.
     *
     * @param createdDate the new created date
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    /**
     * Gets the last updated by.
     *
     * @return the last updated by
     */
    @Column(name="LAST_UPDATED_BY", length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    /**
     * Sets the last updated by.
     *
     * @param lastUpdatedBy the new last updated by
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * Gets the last updated date.
     *
     * @return the last updated date
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    /**
     * Sets the last updated date.
     *
     * @param lastUpdatedDate the new last updated date
     */
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }




}


