package org.gaddiel.model;
// default package
// Generated May 17, 2012 11:25:14 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CollectionsRegister generated by hbm2java
 */
@Entity
@Table(name="collections_register"

)
public class CollectionsRegister  implements java.io.Serializable {


     private Integer collectionId;
     private Integer familyId;
     private Integer custlvPaymentModeId;
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private Integer collectionAmt;
     private String receiptNumber;
     private Date receiptDate;
     private String remarks;
     private String deletedFlag;

    public CollectionsRegister() {
    }

	
    public CollectionsRegister(Date createdDate, Date lastUpdatedDate) {
        this.createdDate = createdDate;
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public CollectionsRegister(Integer familyId, Integer custlvPaymentModeId, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, Integer collectionAmt, String receiptNumber, Date receiptDate, String remarks, String deletedFlag) {
       this.familyId = familyId;
       this.custlvPaymentModeId = custlvPaymentModeId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.collectionAmt = collectionAmt;
       this.receiptNumber = receiptNumber;
       this.receiptDate = receiptDate;
       this.remarks = remarks;
       this.deletedFlag = deletedFlag;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="COLLECTION_ID", unique=true, nullable=false)
    public Integer getCollectionId() {
        return this.collectionId;
    }
    
    public void setCollectionId(Integer collectionId) {
        this.collectionId = collectionId;
    }

    
    @Column(name="FAMILY_ID")
    public Integer getFamilyId() {
        return this.familyId;
    }
    
    public void setFamilyId(Integer familyId) {
        this.familyId = familyId;
    }

    
    @Column(name="CUSTLV_PAYMENT_MODE_ID")
    public Integer getCustlvPaymentModeId() {
        return this.custlvPaymentModeId;
    }
    
    public void setCustlvPaymentModeId(Integer custlvPaymentModeId) {
        this.custlvPaymentModeId = custlvPaymentModeId;
    }

    
    @Column(name="CREATED_BY", length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="COLLECTION_AMT")
    public Integer getCollectionAmt() {
        return this.collectionAmt;
    }
    
    public void setCollectionAmt(Integer collectionAmt) {
        this.collectionAmt = collectionAmt;
    }

    
    @Column(name="RECEIPT_NUMBER", length=60)
    public String getReceiptNumber() {
        return this.receiptNumber;
    }
    
    public void setReceiptNumber(String receiptNumber) {
        this.receiptNumber = receiptNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECEIPT_DATE", length=10)
    public Date getReceiptDate() {
        return this.receiptDate;
    }
    
    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }

    
    @Column(name="REMARKS", length=240)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="DELETED_FLAG", length=1)
    public String getDeletedFlag() {
        return this.deletedFlag;
    }
    
    public void setDeletedFlag(String deletedFlag) {
        this.deletedFlag = deletedFlag;
    }




}


