package org.gaddiel.model;
// default package
// Generated Jun 9, 2012 3:01:02 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContributionSchedules generated by hbm2java
 */
@Entity
@Table(name="contribution_schedules")
public class ContributionSchedules  implements java.io.Serializable {


     private Integer contributionScheduleId;
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private Integer custlvCollectionTypeId;
     private Integer custlvFrequencyTypeId;
     private Integer custlvDueDaysId;
     private Integer dueDate;
     private String enabledFlag;
     private Integer contributionAmount;
     private Date startDate;
     private Date endDate;
     private String remarks;

    public ContributionSchedules() {
    }

	
    public ContributionSchedules(Date createdDate, Date lastUpdatedDate) {
        this.createdDate = createdDate;
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public ContributionSchedules(String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, Integer custlvCollectionTypeId, Integer custlvFrequencyTypeId, Integer custlvDueDaysId, Integer dueDate, String enabledFlag, Integer contributionAmount, Date startDate, Date endDate, String remarks) {
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.custlvCollectionTypeId = custlvCollectionTypeId;
       this.custlvFrequencyTypeId = custlvFrequencyTypeId;
       this.custlvDueDaysId = custlvDueDaysId;
       this.dueDate = dueDate;
       this.enabledFlag = enabledFlag;
       this.contributionAmount = contributionAmount;
       this.startDate = startDate;
       this.endDate = endDate;
       this.remarks = remarks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CONTRIBUTION_SCHEDULE_ID", unique=true, nullable=false)
    public Integer getContributionScheduleId() {
        return this.contributionScheduleId;
    }
    
    public void setContributionScheduleId(Integer contributionScheduleId) {
        this.contributionScheduleId = contributionScheduleId;
    }

    
    @Column(name="CREATED_BY", length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="CUSTLV_COLLECTION_TYPE_ID")
    public Integer getCustlvCollectionTypeId() {
        return this.custlvCollectionTypeId;
    }
    
    public void setCustlvCollectionTypeId(Integer custlvCollectionTypeId) {
        this.custlvCollectionTypeId = custlvCollectionTypeId;
    }

    
    @Column(name="CUSTLV_FREQUENCY_TYPE_ID")
    public Integer getCustlvFrequencyTypeId() {
        return this.custlvFrequencyTypeId;
    }
    
    public void setCustlvFrequencyTypeId(Integer custlvFrequencyTypeId) {
        this.custlvFrequencyTypeId = custlvFrequencyTypeId;
    }

    
    @Column(name="CUSTLV_DUE_DAYS_ID")
    public Integer getCustlvDueDaysId() {
        return this.custlvDueDaysId;
    }
    
    public void setCustlvDueDaysId(Integer custlvDueDaysId) {
        this.custlvDueDaysId = custlvDueDaysId;
    }

    
    @Column(name="DUE_DATE")
    public Integer getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Integer dueDate) {
        this.dueDate = dueDate;
    }

    
    @Column(name="ENABLED_FLAG", length=1)
    public String getEnabledFlag() {
        return this.enabledFlag;
    }
    
    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    
    @Column(name="CONTRIBUTION_AMOUNT")
    public Integer getContributionAmount() {
        return this.contributionAmount;
    }
    
    public void setContributionAmount(Integer contributionAmount) {
        this.contributionAmount = contributionAmount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="START_DATE", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="REMARKS", length=240)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


