package org.gaddiel.model;
// default package
// Generated Mar 12, 2012 10:32:31 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// TODO: Auto-generated Javadoc
/**
 * CustomLookupValues generated by hbm2java.
 */
@Entity
@Table(name="custom_lookup_values")
public class CustomLookupValues  implements java.io.Serializable {


     /** The custom lookup value id. */
     private Integer customLookupValueId;
     
     /** The custom lookup category id. */
     private Integer customLookupCategoryId;
     
     /** The custom lookup code. */
     private String customLookupCode;
     
     /** The custom lookup value. */
     private String customLookupValue;
     
     /** The description. */
     private String description;
     
     /** The enabled flag. */
     private String enabledFlag;
     
     /** The start date. */
     private Date startDate;
     
     /** The end date. */
     private Date endDate;
     
     /** The created by. */
     private String createdBy;
     
     /** The created date. */
     private Date createdDate;
     
     /** The last updated by. */
     private String lastUpdatedBy;
     
     /** The last updated date. */
     private Date lastUpdatedDate;
     
     /** The remarks. */
     private String remarks;

    /**
     * Instantiates a new custom lookup values.
     */
    public CustomLookupValues() {
    }

	
    /**
     * Instantiates a new custom lookup values.
     *
     * @param customLookupValue the custom lookup value
     * @param createdDate the created date
     * @param lastUpdatedDate the last updated date
     */
    public CustomLookupValues(String customLookupValue, Date createdDate, Date lastUpdatedDate) {
        this.customLookupValue = customLookupValue;
        this.createdDate = createdDate;
        this.lastUpdatedDate = lastUpdatedDate;
    }
    
    /**
     * Instantiates a new custom lookup values.
     *
     * @param customLookupCategoryId the custom lookup category id
     * @param customLookupCode the custom lookup code
     * @param customLookupValue the custom lookup value
     * @param description the description
     * @param enabledFlag the enabled flag
     * @param startDate the start date
     * @param endDate the end date
     * @param createdBy the created by
     * @param createdDate the created date
     * @param lastUpdatedBy the last updated by
     * @param lastUpdatedDate the last updated date
     * @param remarks the remarks
     */
    public CustomLookupValues(Integer customLookupCategoryId, String customLookupCode, String customLookupValue, String description, String enabledFlag, Date startDate, Date endDate, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String remarks) {
       this.customLookupCategoryId = customLookupCategoryId;
       this.customLookupCode = customLookupCode;
       this.customLookupValue = customLookupValue;
       this.description = description;
       this.enabledFlag = enabledFlag;
       this.startDate = startDate;
       this.endDate = endDate;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.remarks = remarks;
    }
   
     /**
      * Gets the custom lookup value id.
      *
      * @return the custom lookup value id
      */
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CUSTOM_LOOKUP_VALUE_ID", unique=true, nullable=false)
    public Integer getCustomLookupValueId() {
        return this.customLookupValueId;
    }
    
    /**
     * Sets the custom lookup value id.
     *
     * @param customLookupValueId the new custom lookup value id
     */
    public void setCustomLookupValueId(Integer customLookupValueId) {
        this.customLookupValueId = customLookupValueId;
    }

    
    /**
     * Gets the custom lookup category id.
     *
     * @return the custom lookup category id
     */
    @Column(name="CUSTOM_LOOKUP_CATEGORY_ID")
    public Integer getCustomLookupCategoryId() {
        return this.customLookupCategoryId;
    }
    
    /**
     * Sets the custom lookup category id.
     *
     * @param customLookupCategoryId the new custom lookup category id
     */
    public void setCustomLookupCategoryId(Integer customLookupCategoryId) {
        this.customLookupCategoryId = customLookupCategoryId;
    }

    
    /**
     * Gets the custom lookup code.
     *
     * @return the custom lookup code
     */
    @Column(name="CUSTOM_LOOKUP_CODE", length=100)
    public String getCustomLookupCode() {
        return this.customLookupCode;
    }
    
    /**
     * Sets the custom lookup code.
     *
     * @param customLookupCode the new custom lookup code
     */
    public void setCustomLookupCode(String customLookupCode) {
        this.customLookupCode = customLookupCode;
    }

    
    /**
     * Gets the custom lookup value.
     *
     * @return the custom lookup value
     */
    @Column(name="CUSTOM_LOOKUP_VALUE", nullable=false, length=100)
    public String getCustomLookupValue() {
        return this.customLookupValue;
    }
    
    /**
     * Sets the custom lookup value.
     *
     * @param customLookupValue the new custom lookup value
     */
    public void setCustomLookupValue(String customLookupValue) {
        this.customLookupValue = customLookupValue;
    }

    
    /**
     * Gets the description.
     *
     * @return the description
     */
    @Column(name="DESCRIPTION", length=240)
    public String getDescription() {
        return this.description;
    }
    
    /**
     * Sets the description.
     *
     * @param description the new description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    
    /**
     * Gets the enabled flag.
     *
     * @return the enabled flag
     */
    @Column(name="ENABLED_FLAG", length=1)
    public String getEnabledFlag() {
        return this.enabledFlag;
    }
    
    /**
     * Sets the enabled flag.
     *
     * @param enabledFlag the new enabled flag
     */
    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    /**
     * Gets the start date.
     *
     * @return the start date
     */
    @Temporal(TemporalType.DATE)
    @Column(name="START_DATE", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    /**
     * Sets the start date.
     *
     * @param startDate the new start date
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * Gets the end date.
     *
     * @return the end date
     */
    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    /**
     * Sets the end date.
     *
     * @param endDate the new end date
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    /**
     * Gets the created by.
     *
     * @return the created by
     */
    @Column(name="CREATED_BY", length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    /**
     * Sets the created by.
     *
     * @param createdBy the new created by
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Gets the created date.
     *
     * @return the created date
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    /**
     * Sets the created date.
     *
     * @param createdDate the new created date
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    /**
     * Gets the last updated by.
     *
     * @return the last updated by
     */
    @Column(name="LAST_UPDATED_BY", length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    /**
     * Sets the last updated by.
     *
     * @param lastUpdatedBy the new last updated by
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * Gets the last updated date.
     *
     * @return the last updated date
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    /**
     * Sets the last updated date.
     *
     * @param lastUpdatedDate the new last updated date
     */
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    /**
     * Gets the remarks.
     *
     * @return the remarks
     */
    @Column(name="REMARKS", length=240)
    public String getRemarks() {
        return this.remarks;
    }
    
    /**
     * Sets the remarks.
     *
     * @param remarks the new remarks
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


