package org.gaddiel.model;
// default package
// Generated May 17, 2012 11:25:14 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Family generated by hbm2java
 */
@Entity
@Table(name="family"
   , uniqueConstraints = @UniqueConstraint(columnNames={"FAMILY_NAME", "FAMILY_HEAD_NAME"}) 
)
public class Family  implements java.io.Serializable {


     private Integer familyId;
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String familyName;
     private String familyHeadName;
     private Date dateOfEntry;
     private Integer familyGrossIncome;
     private String familyContactPhoneNo;
     private String alternateContactPhoneNo;
     private String familyEmailId;
     private String alternateEmailId;
     private Integer familyCurrentSubscription;
     private Date subscriptionPaidUptoDate;
     private Integer familyHeadMemberId;
     private Integer custlvPrefContactModeId;
     private Integer custlvPrefPayModeId;
     private Integer custlvLanguageId;
     private Integer custlvAnbiamId;
     private Integer custlvSubstationId;
     private Integer custlvMemberGrpId;
     private Integer custlvCommunityId;
     private Integer custlvCasteId;
     private Integer custlvLiteracyLvlId;
     private Integer custlvIncomeTypeId;
     private Integer custlvHouseTypeId;
     private Integer custlvEntryTypeId;
     private Integer custlvExitTypeId;
     private Integer custlvExitReasonId;
     private Integer custlvPrefContModeId;
     private String agriLandAreaOwned;
     private String housingLandAreaOwned;
     private String busineesAreaOwned;
     private String feastFeePayer;
     private String donationPayer;
     private String specialFeePayer;
     private Integer totalMaleReligMembers;
     private Integer totalFemaleReligMembers;
     private Integer totalSemiReligMembers;
     private String doorNumber;
     private String suiteNumber;
     private String floorNumber;
     private String builidingName;
     private String streetName;
     private String addressArea;
     private String addressZone;
     private String postalZone;
     private Integer custlvCountyId;
     private Integer custlvDistrictId;
     private Integer custlvStateLocationId;
     private Integer custlvProvinceId;
     private Integer custlvCountryId;
     private String postalCode;
     private String landMark1;
     private String landMark2;
     private Date dateOfExit;
     private String remarks;
     private String confidentialInformation;
     private String familyDeletedFlag;

    public Family() {
    }

	
    public Family(Date createdDate, Date lastUpdatedDate, String familyName, String familyHeadName) {
        this.createdDate = createdDate;
        this.lastUpdatedDate = lastUpdatedDate;
        this.familyName = familyName;
        this.familyHeadName = familyHeadName;
    }
    public Family(String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String familyName, String familyHeadName, Date dateOfEntry, Integer familyGrossIncome, String familyContactPhoneNo, String alternateContactPhoneNo, String familyEmailId, String alternateEmailId, Integer familyCurrentSubscription, Date subscriptionPaidUptoDate, Integer familyHeadMemberId, Integer custlvPrefContactModeId, Integer custlvPrefPayModeId, Integer custlvLanguageId, Integer custlvAnbiamId, Integer custlvSubstationId, Integer custlvMemberGrpId, Integer custlvCommunityId, Integer custlvCasteId, Integer custlvLiteracyLvlId, Integer custlvIncomeTypeId, Integer custlvHouseTypeId, Integer custlvEntryTypeId, Integer custlvExitTypeId, Integer custlvExitReasonId, Integer custlvPrefContModeId, String agriLandAreaOwned, String housingLandAreaOwned, String busineesAreaOwned, String feastFeePayer, String donationPayer, String specialFeePayer, Integer totalMaleReligMembers, Integer totalFemaleReligMembers, Integer totalSemiReligMembers, String doorNumber, String suiteNumber, String floorNumber, String builidingName, String streetName, String addressArea, String addressZone, String postalZone, Integer custlvCountyId, Integer custlvDistrictId, Integer custlvStateLocationId, Integer custlvProvinceId, Integer custlvCountryId, String postalCode, String landMark1, String landMark2, Date dateOfExit, String remarks, String confidentialInformation, String familyDeletedFlag) {
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.familyName = familyName;
       this.familyHeadName = familyHeadName;
       this.dateOfEntry = dateOfEntry;
       this.familyGrossIncome = familyGrossIncome;
       this.familyContactPhoneNo = familyContactPhoneNo;
       this.alternateContactPhoneNo = alternateContactPhoneNo;
       this.familyEmailId = familyEmailId;
       this.alternateEmailId = alternateEmailId;
       this.familyCurrentSubscription = familyCurrentSubscription;
       this.subscriptionPaidUptoDate = subscriptionPaidUptoDate;
       this.familyHeadMemberId = familyHeadMemberId;
       this.custlvPrefContactModeId = custlvPrefContactModeId;
       this.custlvPrefPayModeId = custlvPrefPayModeId;
       this.custlvLanguageId = custlvLanguageId;
       this.custlvAnbiamId = custlvAnbiamId;
       this.custlvSubstationId = custlvSubstationId;
       this.custlvMemberGrpId = custlvMemberGrpId;
       this.custlvCommunityId = custlvCommunityId;
       this.custlvCasteId = custlvCasteId;
       this.custlvLiteracyLvlId = custlvLiteracyLvlId;
       this.custlvIncomeTypeId = custlvIncomeTypeId;
       this.custlvHouseTypeId = custlvHouseTypeId;
       this.custlvEntryTypeId = custlvEntryTypeId;
       this.custlvExitTypeId = custlvExitTypeId;
       this.custlvExitReasonId = custlvExitReasonId;
       this.custlvPrefContModeId = custlvPrefContModeId;
       this.agriLandAreaOwned = agriLandAreaOwned;
       this.housingLandAreaOwned = housingLandAreaOwned;
       this.busineesAreaOwned = busineesAreaOwned;
       this.feastFeePayer = feastFeePayer;
       this.donationPayer = donationPayer;
       this.specialFeePayer = specialFeePayer;
       this.totalMaleReligMembers = totalMaleReligMembers;
       this.totalFemaleReligMembers = totalFemaleReligMembers;
       this.totalSemiReligMembers = totalSemiReligMembers;
       this.doorNumber = doorNumber;
       this.suiteNumber = suiteNumber;
       this.floorNumber = floorNumber;
       this.builidingName = builidingName;
       this.streetName = streetName;
       this.addressArea = addressArea;
       this.addressZone = addressZone;
       this.postalZone = postalZone;
       this.custlvCountyId = custlvCountyId;
       this.custlvDistrictId = custlvDistrictId;
       this.custlvStateLocationId = custlvStateLocationId;
       this.custlvProvinceId = custlvProvinceId;
       this.custlvCountryId = custlvCountryId;
       this.postalCode = postalCode;
       this.landMark1 = landMark1;
       this.landMark2 = landMark2;
       this.dateOfExit = dateOfExit;
       this.remarks = remarks;
       this.confidentialInformation = confidentialInformation;
       this.familyDeletedFlag = familyDeletedFlag;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="FAMILY_ID", unique=true, nullable=false)
    public Integer getFamilyId() {
        return this.familyId;
    }
    
    public void setFamilyId(Integer familyId) {
        this.familyId = familyId;
    }

    
    @Column(name="CREATED_BY", length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="FAMILY_NAME", nullable=false, length=240)
    public String getFamilyName() {
        return this.familyName;
    }
    
    public void setFamilyName(String familyName) {
        this.familyName = familyName;
    }

    
    @Column(name="FAMILY_HEAD_NAME", nullable=false, length=60)
    public String getFamilyHeadName() {
        return this.familyHeadName;
    }
    
    public void setFamilyHeadName(String familyHeadName) {
        this.familyHeadName = familyHeadName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_OF_ENTRY", length=10)
    public Date getDateOfEntry() {
        return this.dateOfEntry;
    }
    
    public void setDateOfEntry(Date dateOfEntry) {
        this.dateOfEntry = dateOfEntry;
    }

    
    @Column(name="FAMILY_GROSS_INCOME")
    public Integer getFamilyGrossIncome() {
        return this.familyGrossIncome;
    }
    
    public void setFamilyGrossIncome(Integer familyGrossIncome) {
        this.familyGrossIncome = familyGrossIncome;
    }

    
    @Column(name="FAMILY_CONTACT_PHONE_NO", length=30)
    public String getFamilyContactPhoneNo() {
        return this.familyContactPhoneNo;
    }
    
    public void setFamilyContactPhoneNo(String familyContactPhoneNo) {
        this.familyContactPhoneNo = familyContactPhoneNo;
    }

    
    @Column(name="ALTERNATE_CONTACT_PHONE_NO", length=30)
    public String getAlternateContactPhoneNo() {
        return this.alternateContactPhoneNo;
    }
    
    public void setAlternateContactPhoneNo(String alternateContactPhoneNo) {
        this.alternateContactPhoneNo = alternateContactPhoneNo;
    }

    
    @Column(name="FAMILY_EMAIL_ID", length=60)
    public String getFamilyEmailId() {
        return this.familyEmailId;
    }
    
    public void setFamilyEmailId(String familyEmailId) {
        this.familyEmailId = familyEmailId;
    }

    
    @Column(name="ALTERNATE_EMAIL_ID", length=60)
    public String getAlternateEmailId() {
        return this.alternateEmailId;
    }
    
    public void setAlternateEmailId(String alternateEmailId) {
        this.alternateEmailId = alternateEmailId;
    }

    
    @Column(name="FAMILY_CURRENT_SUBSCRIPTION")
    public Integer getFamilyCurrentSubscription() {
        return this.familyCurrentSubscription;
    }
    
    public void setFamilyCurrentSubscription(Integer familyCurrentSubscription) {
        this.familyCurrentSubscription = familyCurrentSubscription;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SUBSCRIPTION_PAID_UPTO_DATE", length=10)
    public Date getSubscriptionPaidUptoDate() {
        return this.subscriptionPaidUptoDate;
    }
    
    public void setSubscriptionPaidUptoDate(Date subscriptionPaidUptoDate) {
        this.subscriptionPaidUptoDate = subscriptionPaidUptoDate;
    }

    
    @Column(name="FAMILY_HEAD_MEMBER_ID")
    public Integer getFamilyHeadMemberId() {
        return this.familyHeadMemberId;
    }
    
    public void setFamilyHeadMemberId(Integer familyHeadMemberId) {
        this.familyHeadMemberId = familyHeadMemberId;
    }

    
    @Column(name="CUSTLV_PREF_CONTACT_MODE_ID")
    public Integer getCustlvPrefContactModeId() {
        return this.custlvPrefContactModeId;
    }
    
    public void setCustlvPrefContactModeId(Integer custlvPrefContactModeId) {
        this.custlvPrefContactModeId = custlvPrefContactModeId;
    }

    
    @Column(name="CUSTLV_PREF_PAY_MODE_ID")
    public Integer getCustlvPrefPayModeId() {
        return this.custlvPrefPayModeId;
    }
    
    public void setCustlvPrefPayModeId(Integer custlvPrefPayModeId) {
        this.custlvPrefPayModeId = custlvPrefPayModeId;
    }

    
    @Column(name="CUSTLV_LANGUAGE_ID")
    public Integer getCustlvLanguageId() {
        return this.custlvLanguageId;
    }
    
    public void setCustlvLanguageId(Integer custlvLanguageId) {
        this.custlvLanguageId = custlvLanguageId;
    }

    
    @Column(name="CUSTLV_ANBIAM_ID")
    public Integer getCustlvAnbiamId() {
        return this.custlvAnbiamId;
    }
    
    public void setCustlvAnbiamId(Integer custlvAnbiamId) {
        this.custlvAnbiamId = custlvAnbiamId;
    }

    
    @Column(name="CUSTLV_SUBSTATION_ID")
    public Integer getCustlvSubstationId() {
        return this.custlvSubstationId;
    }
    
    public void setCustlvSubstationId(Integer custlvSubstationId) {
        this.custlvSubstationId = custlvSubstationId;
    }

    
    @Column(name="CUSTLV_MEMBER_GRP_ID")
    public Integer getCustlvMemberGrpId() {
        return this.custlvMemberGrpId;
    }
    
    public void setCustlvMemberGrpId(Integer custlvMemberGrpId) {
        this.custlvMemberGrpId = custlvMemberGrpId;
    }

    
    @Column(name="CUSTLV_COMMUNITY_ID")
    public Integer getCustlvCommunityId() {
        return this.custlvCommunityId;
    }
    
    public void setCustlvCommunityId(Integer custlvCommunityId) {
        this.custlvCommunityId = custlvCommunityId;
    }

    
    @Column(name="CUSTLV_CASTE_ID")
    public Integer getCustlvCasteId() {
        return this.custlvCasteId;
    }
    
    public void setCustlvCasteId(Integer custlvCasteId) {
        this.custlvCasteId = custlvCasteId;
    }

    
    @Column(name="CUSTLV_LITERACY_LVL_ID")
    public Integer getCustlvLiteracyLvlId() {
        return this.custlvLiteracyLvlId;
    }
    
    public void setCustlvLiteracyLvlId(Integer custlvLiteracyLvlId) {
        this.custlvLiteracyLvlId = custlvLiteracyLvlId;
    }

    
    @Column(name="CUSTLV_INCOME_TYPE_ID")
    public Integer getCustlvIncomeTypeId() {
        return this.custlvIncomeTypeId;
    }
    
    public void setCustlvIncomeTypeId(Integer custlvIncomeTypeId) {
        this.custlvIncomeTypeId = custlvIncomeTypeId;
    }

    
    @Column(name="CUSTLV_HOUSE_TYPE_ID")
    public Integer getCustlvHouseTypeId() {
        return this.custlvHouseTypeId;
    }
    
    public void setCustlvHouseTypeId(Integer custlvHouseTypeId) {
        this.custlvHouseTypeId = custlvHouseTypeId;
    }

    
    @Column(name="CUSTLV_ENTRY_TYPE_ID")
    public Integer getCustlvEntryTypeId() {
        return this.custlvEntryTypeId;
    }
    
    public void setCustlvEntryTypeId(Integer custlvEntryTypeId) {
        this.custlvEntryTypeId = custlvEntryTypeId;
    }

    
    @Column(name="CUSTLV_EXIT_TYPE_ID")
    public Integer getCustlvExitTypeId() {
        return this.custlvExitTypeId;
    }
    
    public void setCustlvExitTypeId(Integer custlvExitTypeId) {
        this.custlvExitTypeId = custlvExitTypeId;
    }

    
    @Column(name="CUSTLV_EXIT_REASON_ID")
    public Integer getCustlvExitReasonId() {
        return this.custlvExitReasonId;
    }
    
    public void setCustlvExitReasonId(Integer custlvExitReasonId) {
        this.custlvExitReasonId = custlvExitReasonId;
    }

    
    @Column(name="CUSTLV_PREF_CONT_MODE_ID")
    public Integer getCustlvPrefContModeId() {
        return this.custlvPrefContModeId;
    }
    
    public void setCustlvPrefContModeId(Integer custlvPrefContModeId) {
        this.custlvPrefContModeId = custlvPrefContModeId;
    }

    
    @Column(name="AGRI_LAND_AREA_OWNED", length=60)
    public String getAgriLandAreaOwned() {
        return this.agriLandAreaOwned;
    }
    
    public void setAgriLandAreaOwned(String agriLandAreaOwned) {
        this.agriLandAreaOwned = agriLandAreaOwned;
    }

    
    @Column(name="HOUSING_LAND_AREA_OWNED", length=60)
    public String getHousingLandAreaOwned() {
        return this.housingLandAreaOwned;
    }
    
    public void setHousingLandAreaOwned(String housingLandAreaOwned) {
        this.housingLandAreaOwned = housingLandAreaOwned;
    }

    
    @Column(name="BUSINEES_AREA_OWNED", length=60)
    public String getBusineesAreaOwned() {
        return this.busineesAreaOwned;
    }
    
    public void setBusineesAreaOwned(String busineesAreaOwned) {
        this.busineesAreaOwned = busineesAreaOwned;
    }

    
    @Column(name="FEAST_FEE_PAYER", length=1)
    public String getFeastFeePayer() {
        return this.feastFeePayer;
    }
    
    public void setFeastFeePayer(String feastFeePayer) {
        this.feastFeePayer = feastFeePayer;
    }

    
    @Column(name="DONATION_PAYER", length=1)
    public String getDonationPayer() {
        return this.donationPayer;
    }
    
    public void setDonationPayer(String donationPayer) {
        this.donationPayer = donationPayer;
    }

    
    @Column(name="SPECIAL_FEE_PAYER", length=1)
    public String getSpecialFeePayer() {
        return this.specialFeePayer;
    }
    
    public void setSpecialFeePayer(String specialFeePayer) {
        this.specialFeePayer = specialFeePayer;
    }

    
    @Column(name="TOTAL_MALE_RELIG_MEMBERS")
    public Integer getTotalMaleReligMembers() {
        return this.totalMaleReligMembers;
    }
    
    public void setTotalMaleReligMembers(Integer totalMaleReligMembers) {
        this.totalMaleReligMembers = totalMaleReligMembers;
    }

    
    @Column(name="TOTAL_FEMALE_RELIG_MEMBERS")
    public Integer getTotalFemaleReligMembers() {
        return this.totalFemaleReligMembers;
    }
    
    public void setTotalFemaleReligMembers(Integer totalFemaleReligMembers) {
        this.totalFemaleReligMembers = totalFemaleReligMembers;
    }

    
    @Column(name="TOTAL_SEMI_RELIG_MEMBERS")
    public Integer getTotalSemiReligMembers() {
        return this.totalSemiReligMembers;
    }
    
    public void setTotalSemiReligMembers(Integer totalSemiReligMembers) {
        this.totalSemiReligMembers = totalSemiReligMembers;
    }

    
    @Column(name="DOOR_NUMBER", length=10)
    public String getDoorNumber() {
        return this.doorNumber;
    }
    
    public void setDoorNumber(String doorNumber) {
        this.doorNumber = doorNumber;
    }

    
    @Column(name="SUITE_NUMBER", length=10)
    public String getSuiteNumber() {
        return this.suiteNumber;
    }
    
    public void setSuiteNumber(String suiteNumber) {
        this.suiteNumber = suiteNumber;
    }

    
    @Column(name="FLOOR_NUMBER", length=10)
    public String getFloorNumber() {
        return this.floorNumber;
    }
    
    public void setFloorNumber(String floorNumber) {
        this.floorNumber = floorNumber;
    }

    
    @Column(name="BUILIDING_NAME", length=60)
    public String getBuilidingName() {
        return this.builidingName;
    }
    
    public void setBuilidingName(String builidingName) {
        this.builidingName = builidingName;
    }

    
    @Column(name="STREET_NAME", length=100)
    public String getStreetName() {
        return this.streetName;
    }
    
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    
    @Column(name="ADDRESS_AREA", length=60)
    public String getAddressArea() {
        return this.addressArea;
    }
    
    public void setAddressArea(String addressArea) {
        this.addressArea = addressArea;
    }

    
    @Column(name="ADDRESS_ZONE", length=60)
    public String getAddressZone() {
        return this.addressZone;
    }
    
    public void setAddressZone(String addressZone) {
        this.addressZone = addressZone;
    }

    
    @Column(name="POSTAL_ZONE", length=60)
    public String getPostalZone() {
        return this.postalZone;
    }
    
    public void setPostalZone(String postalZone) {
        this.postalZone = postalZone;
    }

    
    @Column(name="CUSTLV_COUNTY_ID")
    public Integer getCustlvCountyId() {
        return this.custlvCountyId;
    }
    
    public void setCustlvCountyId(Integer custlvCountyId) {
        this.custlvCountyId = custlvCountyId;
    }

    
    @Column(name="CUSTLV_DISTRICT_ID")
    public Integer getCustlvDistrictId() {
        return this.custlvDistrictId;
    }
    
    public void setCustlvDistrictId(Integer custlvDistrictId) {
        this.custlvDistrictId = custlvDistrictId;
    }

    
    @Column(name="CUSTLV_STATE_LOCATION_ID")
    public Integer getCustlvStateLocationId() {
        return this.custlvStateLocationId;
    }
    
    public void setCustlvStateLocationId(Integer custlvStateLocationId) {
        this.custlvStateLocationId = custlvStateLocationId;
    }

    
    @Column(name="CUSTLV_PROVINCE_ID")
    public Integer getCustlvProvinceId() {
        return this.custlvProvinceId;
    }
    
    public void setCustlvProvinceId(Integer custlvProvinceId) {
        this.custlvProvinceId = custlvProvinceId;
    }

    
    @Column(name="CUSTLV_COUNTRY_ID")
    public Integer getCustlvCountryId() {
        return this.custlvCountryId;
    }
    
    public void setCustlvCountryId(Integer custlvCountryId) {
        this.custlvCountryId = custlvCountryId;
    }

    
    @Column(name="POSTAL_CODE", length=60)
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    
    @Column(name="LAND_MARK1", length=200)
    public String getLandMark1() {
        return this.landMark1;
    }
    
    public void setLandMark1(String landMark1) {
        this.landMark1 = landMark1;
    }

    
    @Column(name="LAND_MARK2", length=200)
    public String getLandMark2() {
        return this.landMark2;
    }
    
    public void setLandMark2(String landMark2) {
        this.landMark2 = landMark2;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_OF_EXIT", length=10)
    public Date getDateOfExit() {
        return this.dateOfExit;
    }
    
    public void setDateOfExit(Date dateOfExit) {
        this.dateOfExit = dateOfExit;
    }

    
    @Column(name="REMARKS", length=240)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="CONFIDENTIAL_INFORMATION", length=4000)
    public String getConfidentialInformation() {
        return this.confidentialInformation;
    }
    
    public void setConfidentialInformation(String confidentialInformation) {
        this.confidentialInformation = confidentialInformation;
    }

    
    @Column(name="FAMILY_DELETED_FLAG", length=1)
    public String getFamilyDeletedFlag() {
        return this.familyDeletedFlag;
    }
    
    public void setFamilyDeletedFlag(String familyDeletedFlag) {
        this.familyDeletedFlag = familyDeletedFlag;
    }




}


