package org.gaddiel.model;
// default package
// Generated Mar 12, 2012 10:32:31 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// TODO: Auto-generated Javadoc
/**
 * SystemSubscriberFunctions generated by hbm2java.
 */
@Entity
@Table(name="system_subscriber_functions")

public class SystemSubscriberFunctions  implements java.io.Serializable {


     /** The subscriber function id. */
     private Integer subscriberFunctionId;
     
     /** The subscriber id. */
     private Integer subscriberId;
     
     /** The system function lv id. */
     private Integer systemFunctionLvId;
     
     /** The function name. */
     private String functionName;
     
     /** The description. */
     private String description;
     
     /** The enabled flag. */
     private String enabledFlag;
     
     /** The start date. */
     private Date startDate;
     
     /** The end date. */
     private Date endDate;
     
     /** The created by. */
     private String createdBy;
     
     /** The created date. */
     private Date createdDate;
     
     /** The last updated by. */
     private String lastUpdatedBy;
     
     /** The last updated date. */
     private Date lastUpdatedDate;
     
     /** The remarks. */
     private String remarks;

    /**
     * Instantiates a new system subscriber functions.
     */
    public SystemSubscriberFunctions() {
    }

	
    /**
     * Instantiates a new system subscriber functions.
     *
     * @param createdDate the created date
     * @param lastUpdatedDate the last updated date
     */
    public SystemSubscriberFunctions(Date createdDate, Date lastUpdatedDate) {
        this.createdDate = createdDate;
        this.lastUpdatedDate = lastUpdatedDate;
    }
    
    /**
     * Instantiates a new system subscriber functions.
     *
     * @param subscriberId the subscriber id
     * @param systemFunctionLvId the system function lv id
     * @param functionName the function name
     * @param description the description
     * @param enabledFlag the enabled flag
     * @param startDate the start date
     * @param endDate the end date
     * @param createdBy the created by
     * @param createdDate the created date
     * @param lastUpdatedBy the last updated by
     * @param lastUpdatedDate the last updated date
     * @param remarks the remarks
     */
    public SystemSubscriberFunctions(Integer subscriberId, Integer systemFunctionLvId, String functionName, String description, String enabledFlag, Date startDate, Date endDate, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String remarks) {
       this.subscriberId = subscriberId;
       this.systemFunctionLvId = systemFunctionLvId;
       this.functionName = functionName;
       this.description = description;
       this.enabledFlag = enabledFlag;
       this.startDate = startDate;
       this.endDate = endDate;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.remarks = remarks;
    }
   
     /**
      * Gets the subscriber function id.
      *
      * @return the subscriber function id
      */
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SUBSCRIBER_FUNCTION_ID", unique=true, nullable=false)
    public Integer getSubscriberFunctionId() {
        return this.subscriberFunctionId;
    }
    
    /**
     * Sets the subscriber function id.
     *
     * @param subscriberFunctionId the new subscriber function id
     */
    public void setSubscriberFunctionId(Integer subscriberFunctionId) {
        this.subscriberFunctionId = subscriberFunctionId;
    }

    
    /**
     * Gets the subscriber id.
     *
     * @return the subscriber id
     */
    @Column(name="SUBSCRIBER_ID")
    public Integer getSubscriberId() {
        return this.subscriberId;
    }
    
    /**
     * Sets the subscriber id.
     *
     * @param subscriberId the new subscriber id
     */
    public void setSubscriberId(Integer subscriberId) {
        this.subscriberId = subscriberId;
    }

    
    /**
     * Gets the system function lv id.
     *
     * @return the system function lv id
     */
    @Column(name="SYSTEM_FUNCTION_LV_ID")
    public Integer getSystemFunctionLvId() {
        return this.systemFunctionLvId;
    }
    
    /**
     * Sets the system function lv id.
     *
     * @param systemFunctionLvId the new system function lv id
     */
    public void setSystemFunctionLvId(Integer systemFunctionLvId) {
        this.systemFunctionLvId = systemFunctionLvId;
    }

    
    /**
     * Gets the function name.
     *
     * @return the function name
     */
    @Column(name="FUNCTION_NAME", length=120)
    public String getFunctionName() {
        return this.functionName;
    }
    
    /**
     * Sets the function name.
     *
     * @param functionName the new function name
     */
    public void setFunctionName(String functionName) {
        this.functionName = functionName;
    }

    
    /**
     * Gets the description.
     *
     * @return the description
     */
    @Column(name="DESCRIPTION", length=240)
    public String getDescription() {
        return this.description;
    }
    
    /**
     * Sets the description.
     *
     * @param description the new description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    
    /**
     * Gets the enabled flag.
     *
     * @return the enabled flag
     */
    @Column(name="ENABLED_FLAG", length=1)
    public String getEnabledFlag() {
        return this.enabledFlag;
    }
    
    /**
     * Sets the enabled flag.
     *
     * @param enabledFlag the new enabled flag
     */
    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    /**
     * Gets the start date.
     *
     * @return the start date
     */
    @Temporal(TemporalType.DATE)
    @Column(name="START_DATE", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    /**
     * Sets the start date.
     *
     * @param startDate the new start date
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * Gets the end date.
     *
     * @return the end date
     */
    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    /**
     * Sets the end date.
     *
     * @param endDate the new end date
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    /**
     * Gets the created by.
     *
     * @return the created by
     */
    @Column(name="CREATED_BY", length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    /**
     * Sets the created by.
     *
     * @param createdBy the new created by
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Gets the created date.
     *
     * @return the created date
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    /**
     * Sets the created date.
     *
     * @param createdDate the new created date
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    /**
     * Gets the last updated by.
     *
     * @return the last updated by
     */
    @Column(name="LAST_UPDATED_BY", length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    /**
     * Sets the last updated by.
     *
     * @param lastUpdatedBy the new last updated by
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * Gets the last updated date.
     *
     * @return the last updated date
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    /**
     * Sets the last updated date.
     *
     * @param lastUpdatedDate the new last updated date
     */
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    /**
     * Gets the remarks.
     *
     * @return the remarks
     */
    @Column(name="REMARKS", length=240)
    public String getRemarks() {
        return this.remarks;
    }
    
    /**
     * Sets the remarks.
     *
     * @param remarks the new remarks
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


