package org.gaddiel.model;
// default package
// Generated Mar 12, 2012 10:32:31 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// TODO: Auto-generated Javadoc
/**
 * SystemSubscribers generated by hbm2java.
 */
@Entity
@Table(name="system_subscribers")

public class SystemSubscribers  implements java.io.Serializable {


     /** The subscriber id. */
     private Integer subscriberId;
     
     /** The subscriber name. */
     private String subscriberName;
     
     /** The suscriber code. */
     private String suscriberCode;
     
     /** The default url. */
     private String defaultUrl;
     
     /** The secondary url. */
     private String secondaryUrl;
     
     /** The data base id. */
     private Integer dataBaseId;
     
     /** The schema name. */
     private String schemaName;
     
     /** The schema password. */
     private String schemaPassword;
     
     /** The connect string. */
     private String connectString;
     
     /** The enabled flag. */
     private String enabledFlag;
     
     /** The start date. */
     private Date startDate;
     
     /** The end date. */
     private Date endDate;
     
     /** The created by. */
     private String createdBy;
     
     /** The created date. */
     private Date createdDate;
     
     /** The last updated by. */
     private String lastUpdatedBy;
     
     /** The last updated date. */
     private Date lastUpdatedDate;
     
     /** The remarks. */
     private String remarks;

    /**
     * Instantiates a new system subscribers.
     */
    public SystemSubscribers() {
    }

	
    /**
     * Instantiates a new system subscribers.
     *
     * @param createdDate the created date
     * @param lastUpdatedDate the last updated date
     */
    public SystemSubscribers(Date createdDate, Date lastUpdatedDate) {
        this.createdDate = createdDate;
        this.lastUpdatedDate = lastUpdatedDate;
    }
    
    /**
     * Instantiates a new system subscribers.
     *
     * @param subscriberName the subscriber name
     * @param suscriberCode the suscriber code
     * @param defaultUrl the default url
     * @param secondaryUrl the secondary url
     * @param dataBaseId the data base id
     * @param schemaName the schema name
     * @param schemaPassword the schema password
     * @param connectString the connect string
     * @param enabledFlag the enabled flag
     * @param startDate the start date
     * @param endDate the end date
     * @param createdBy the created by
     * @param createdDate the created date
     * @param lastUpdatedBy the last updated by
     * @param lastUpdatedDate the last updated date
     * @param remarks the remarks
     */
    public SystemSubscribers(String subscriberName, String suscriberCode, String defaultUrl, String secondaryUrl, Integer dataBaseId, String schemaName, String schemaPassword, String connectString, String enabledFlag, Date startDate, Date endDate, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String remarks) {
       this.subscriberName = subscriberName;
       this.suscriberCode = suscriberCode;
       this.defaultUrl = defaultUrl;
       this.secondaryUrl = secondaryUrl;
       this.dataBaseId = dataBaseId;
       this.schemaName = schemaName;
       this.schemaPassword = schemaPassword;
       this.connectString = connectString;
       this.enabledFlag = enabledFlag;
       this.startDate = startDate;
       this.endDate = endDate;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.remarks = remarks;
    }
   
     /**
      * Gets the subscriber id.
      *
      * @return the subscriber id
      */
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SUBSCRIBER_ID", unique=true, nullable=false)
    public Integer getSubscriberId() {
        return this.subscriberId;
    }
    
    /**
     * Sets the subscriber id.
     *
     * @param subscriberId the new subscriber id
     */
    public void setSubscriberId(Integer subscriberId) {
        this.subscriberId = subscriberId;
    }

    
    /**
     * Gets the subscriber name.
     *
     * @return the subscriber name
     */
    @Column(name="SUBSCRIBER_NAME", length=120)
    public String getSubscriberName() {
        return this.subscriberName;
    }
    
    /**
     * Sets the subscriber name.
     *
     * @param subscriberName the new subscriber name
     */
    public void setSubscriberName(String subscriberName) {
        this.subscriberName = subscriberName;
    }

    
    /**
     * Gets the suscriber code.
     *
     * @return the suscriber code
     */
    @Column(name="SUSCRIBER_CODE", length=120)
    public String getSuscriberCode() {
        return this.suscriberCode;
    }
    
    /**
     * Sets the suscriber code.
     *
     * @param suscriberCode the new suscriber code
     */
    public void setSuscriberCode(String suscriberCode) {
        this.suscriberCode = suscriberCode;
    }

    
    /**
     * Gets the default url.
     *
     * @return the default url
     */
    @Column(name="DEFAULT_URL", length=240)
    public String getDefaultUrl() {
        return this.defaultUrl;
    }
    
    /**
     * Sets the default url.
     *
     * @param defaultUrl the new default url
     */
    public void setDefaultUrl(String defaultUrl) {
        this.defaultUrl = defaultUrl;
    }

    
    /**
     * Gets the secondary url.
     *
     * @return the secondary url
     */
    @Column(name="SECONDARY_URL", length=240)
    public String getSecondaryUrl() {
        return this.secondaryUrl;
    }
    
    /**
     * Sets the secondary url.
     *
     * @param secondaryUrl the new secondary url
     */
    public void setSecondaryUrl(String secondaryUrl) {
        this.secondaryUrl = secondaryUrl;
    }

    
    /**
     * Gets the data base id.
     *
     * @return the data base id
     */
    @Column(name="DATA_BASE_ID")
    public Integer getDataBaseId() {
        return this.dataBaseId;
    }
    
    /**
     * Sets the data base id.
     *
     * @param dataBaseId the new data base id
     */
    public void setDataBaseId(Integer dataBaseId) {
        this.dataBaseId = dataBaseId;
    }

    
    /**
     * Gets the schema name.
     *
     * @return the schema name
     */
    @Column(name="SCHEMA_NAME", length=240)
    public String getSchemaName() {
        return this.schemaName;
    }
    
    /**
     * Sets the schema name.
     *
     * @param schemaName the new schema name
     */
    public void setSchemaName(String schemaName) {
        this.schemaName = schemaName;
    }

    
    /**
     * Gets the schema password.
     *
     * @return the schema password
     */
    @Column(name="SCHEMA_PASSWORD", length=240)
    public String getSchemaPassword() {
        return this.schemaPassword;
    }
    
    /**
     * Sets the schema password.
     *
     * @param schemaPassword the new schema password
     */
    public void setSchemaPassword(String schemaPassword) {
        this.schemaPassword = schemaPassword;
    }

    
    /**
     * Gets the connect string.
     *
     * @return the connect string
     */
    @Column(name="CONNECT_STRING", length=240)
    public String getConnectString() {
        return this.connectString;
    }
    
    /**
     * Sets the connect string.
     *
     * @param connectString the new connect string
     */
    public void setConnectString(String connectString) {
        this.connectString = connectString;
    }

    
    /**
     * Gets the enabled flag.
     *
     * @return the enabled flag
     */
    @Column(name="ENABLED_FLAG", length=1)
    public String getEnabledFlag() {
        return this.enabledFlag;
    }
    
    /**
     * Sets the enabled flag.
     *
     * @param enabledFlag the new enabled flag
     */
    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    /**
     * Gets the start date.
     *
     * @return the start date
     */
    @Temporal(TemporalType.DATE)
    @Column(name="START_DATE", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    /**
     * Sets the start date.
     *
     * @param startDate the new start date
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * Gets the end date.
     *
     * @return the end date
     */
    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    /**
     * Sets the end date.
     *
     * @param endDate the new end date
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    /**
     * Gets the created by.
     *
     * @return the created by
     */
    @Column(name="CREATED_BY", length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    /**
     * Sets the created by.
     *
     * @param createdBy the new created by
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Gets the created date.
     *
     * @return the created date
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    /**
     * Sets the created date.
     *
     * @param createdDate the new created date
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    /**
     * Gets the last updated by.
     *
     * @return the last updated by
     */
    @Column(name="LAST_UPDATED_BY", length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    /**
     * Sets the last updated by.
     *
     * @param lastUpdatedBy the new last updated by
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * Gets the last updated date.
     *
     * @return the last updated date
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    /**
     * Sets the last updated date.
     *
     * @param lastUpdatedDate the new last updated date
     */
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    /**
     * Gets the remarks.
     *
     * @return the remarks
     */
    @Column(name="REMARKS", length=240)
    public String getRemarks() {
        return this.remarks;
    }
    
    /**
     * Sets the remarks.
     *
     * @param remarks the new remarks
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


