// default package
// Generated May 11, 2012 4:28:22 PM by Hibernate Tools 3.4.0.CR1
package org.gaddiel.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SystemUsers generated by hbm2java
 */
@Entity
@Table(name="system_users", uniqueConstraints = @UniqueConstraint(columnNames={"USER_NAME", "SUBSCRIBER_ID"}) 
)
public class SystemUsers  implements java.io.Serializable {


     private Integer userId;
     private Integer subscriberId;
     private String userName;
     private String userPassword;
     private String encryptedPassword;
     private Date lastSuccessLoginDate;
     private Date lastFailedLoginDate;
     private Date nextPasswordChangeDate;
     private String enabledFlag;
     private Date startDate;
     private Date endDate;
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String lastActivityDesc;
     private String remarks;
     private int roleId;
     private String deleteFlag;

    public SystemUsers() {
    }

	
    public SystemUsers(String userName, String userPassword, String encryptedPassword, Date lastFailedLoginDate, Date createdDate, Date lastUpdatedDate, int roleId) {
        this.userName = userName;
        this.userPassword = userPassword;
        this.encryptedPassword = encryptedPassword;
        this.lastFailedLoginDate = lastFailedLoginDate;
        this.createdDate = createdDate;
        this.lastUpdatedDate = lastUpdatedDate;
        this.roleId = roleId;
    }
    public SystemUsers(Integer subscriberId, String userName, String userPassword, String encryptedPassword, Date lastSuccessLoginDate, Date lastFailedLoginDate, Date nextPasswordChangeDate, String enabledFlag, Date startDate, Date endDate, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String lastActivityDesc, String remarks, int roleId, String deleteFlag) {
       this.subscriberId = subscriberId;
       this.userName = userName;
       this.userPassword = userPassword;
       this.encryptedPassword = encryptedPassword;
       this.lastSuccessLoginDate = lastSuccessLoginDate;
       this.lastFailedLoginDate = lastFailedLoginDate;
       this.nextPasswordChangeDate = nextPasswordChangeDate;
       this.enabledFlag = enabledFlag;
       this.startDate = startDate;
       this.endDate = endDate;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastActivityDesc = lastActivityDesc;
       this.remarks = remarks;
       this.roleId = roleId;
       this.deleteFlag = deleteFlag;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="USER_ID", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="SUBSCRIBER_ID")
    public Integer getSubscriberId() {
        return this.subscriberId;
    }
    
    public void setSubscriberId(Integer subscriberId) {
        this.subscriberId = subscriberId;
    }

    
    @Column(name="USER_NAME", nullable=false, length=60)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="USER_PASSWORD", nullable=false, length=240)
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    
    @Column(name="ENCRYPTED_PASSWORD", nullable=false, length=240)
    public String getEncryptedPassword() {
        return this.encryptedPassword;
    }
    
    public void setEncryptedPassword(String encryptedPassword) {
        this.encryptedPassword = encryptedPassword;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_SUCCESS_LOGIN_DATE", length=10)
    public Date getLastSuccessLoginDate() {
        return this.lastSuccessLoginDate;
    }
    
    public void setLastSuccessLoginDate(Date lastSuccessLoginDate) {
        this.lastSuccessLoginDate = lastSuccessLoginDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_FAILED_LOGIN_DATE",  length=19)
    public Date getLastFailedLoginDate() {
        return this.lastFailedLoginDate;
    }
    
    public void setLastFailedLoginDate(Date lastFailedLoginDate) {
        this.lastFailedLoginDate = lastFailedLoginDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NEXT_PASSWORD_CHANGE_DATE", length=10)
    public Date getNextPasswordChangeDate() {
        return this.nextPasswordChangeDate;
    }
    
    public void setNextPasswordChangeDate(Date nextPasswordChangeDate) {
        this.nextPasswordChangeDate = nextPasswordChangeDate;
    }

    
    @Column(name="ENABLED_FLAG", length=1)
    public String getEnabledFlag() {
        return this.enabledFlag;
    }
    
    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="START_DATE", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="CREATED_BY", length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="LAST_ACTIVITY_DESC", length=240)
    public String getLastActivityDesc() {
        return this.lastActivityDesc;
    }
    
    public void setLastActivityDesc(String lastActivityDesc) {
        this.lastActivityDesc = lastActivityDesc;
    }

    
    @Column(name="REMARKS", length=240)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="ROLE_ID", nullable=false)
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    
    @Column(name="DELETE_FLAG", length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }




}


