// default package
// Generated Apr 18, 2012 3:52:07 PM by Hibernate Tools 3.4.0.CR1
package org.gaddiel.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import java.sql.Blob;

/**
 * TempPagination generated by hbm2java
 */
@Entity
@Table(name="temp_pagination")
public class TempPagination  implements java.io.Serializable {


     private Integer tempId;
     private Blob tempVal;
     private String sessionId;

    public TempPagination() {
    }

    public TempPagination(Blob tempVal) {
       this.tempVal = tempVal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TEMP_ID", unique=true, nullable=false)
    public Integer getTempId() {
        return this.tempId;
    }
    
    public void setTempId(Integer tempId) {
        this.tempId = tempId;
    }

    @Column(name="SESSION_ID")
    public String getSessionId() {
		return sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name="TEMP_VAL")
    public Blob getTempVal() {
        return this.tempVal;
    }
    
    public void setTempVal(Blob tempVal) {
        this.tempVal = tempVal;
    }




}


